# This is a basic workflow to help you get started with Actions
name: Question Fetch
on:
  schedule: # Run workflow automatically
    - cron: '* * * * *' # Runs on 00:00 UTC everyday
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-question:
    name: Update readme and add problem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "PROBLEM"
          feed_list: "https://gist.github.com/search?q=%23blog+user%3AVyvy-vi"
          max_post_count: 1
          disable_sort : true
          
          
